ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'


# Nouveau server WP2
# Wordpress 2
Vagrant.configure("2") do |config|
    config.vm.define "exam2_WP2" do |exam2_WP2|
    exam2_WP2.vm.network :private_network, ip: "192.168.110.12", netmask: 24
    #exam2_WP2.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: false
    #exam2_WP2.vm.network "forwarded_port", guest: 443, host: 2443, auto_correct: false
    exam2_WP2.vm.provider "docker" do |exam2_WP2|
    exam2_WP2.build_dir = "."
#    exam2_WP2.image = "exam2_nx_img:exam2_nx_img""
    exam2_WP2.has_ssh = true
    exam2_WP2.privileged = true
    exam2_WP2.create_args = ["-v", "/sys/fs/cgroup:/sys/fs/cgroup:ro"]
    exam2_WP2.name = "exam2_infra2_WP2"
    exam2_WP2.volumes = [
      "/infra2_exam2/apps:/infra2_exam2/apps",
      "/infra2_exam2/logs:/infra2_exam2/logs",
      "/infra2_exam2/backup:/infra2_exam2/backup",
      "/etc/letsencrypt:/etc/letsencrypt"
       ]
   end
  end
end



