ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'


# Nouveau server mariaDB
Vagrant.configure("2") do |config|
    config.vm.define "exam2_DB" do |exam2_DB|
    exam2_DB.vm.network :private_network, ip: "192.168.110.13", netmask: 24
#    exam2_DB.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: false
    exam2_DB.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct: false
    exam2_DB.vm.provider "docker" do |exam2_DB|
    exam2_DB.build_dir = "."
    exam2_DB.has_ssh = true
    exam2_DB.privileged = true
    exam2_DB.create_args = ["-v", "/sys/fs/cgroup:/sys/fs/cgroup:ro"]
    exam2_DB.name = "exam2_infra2_DB"
    exam2_DB.volumes = [
      "/infra2_exam2/apps:/infra2_exam2/apps",
      "/infra2_exam2/logs:/infra2_exam2/logs",
      "/infra2_exam2/backup/:/infra2_exam2/backup"
       ]
   end
  end
end



